/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop_gestionebiblioteca;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author Benedetto
 */
public class GestioneBiblioteca_GUI_Register extends javax.swing.JFrame {

    /**
     * Creates new form GestioneBiblioteca_GUI_Login
     */
    public GestioneBiblioteca_GUI_Register() {
        
            initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabelCloseButton = new javax.swing.JLabel();
        jLogoBiblioteca = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanelLoginBox = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jIconLogin = new javax.swing.JLabel();
        jTextCognome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JToggleButton();
        jTextEmail = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelCognome = new javax.swing.JLabel();
        jPasswordConferma = new javax.swing.JPasswordField();
        jLabelPassword1 = new javax.swing.JLabel();
        jLabelNomeErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 105, 64));
        setForeground(new java.awt.Color(23, 105, 64));
        setLocation(new java.awt.Point(50, 50));
        setMaximumSize(new java.awt.Dimension(1400, 768));
        setMinimumSize(new java.awt.Dimension(1200, 768));
        setUndecorated(true);
        setResizable(false);

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.setMaximumSize(new java.awt.Dimension(1400, 120));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(1400, 120));
        jPanelHeader.setName(""); // NOI18N
        jPanelHeader.setPreferredSize(new java.awt.Dimension(1400, 120));

        jLabelCloseButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Benedetto\\Documents\\NetBeansProjects\\OOP_GestioneBiblioteca\\src\\close.png")); // NOI18N
        jLabelCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseButtonMouseExited(evt);
            }
        });

        jLogoBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_biblioteca.png"))); // NOI18N

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLogoBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                .addComponent(jLabelCloseButton)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCloseButton))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLogoBiblioteca)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanelBody.setBackground(new java.awt.Color(92, 184, 147));
        jPanelBody.setMaximumSize(new java.awt.Dimension(1400, 480));
        jPanelBody.setMinimumSize(new java.awt.Dimension(1400, 480));
        jPanelBody.setPreferredSize(new java.awt.Dimension(1400, 480));
        jPanelBody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBodyMouseClicked(evt);
            }
        });

        jPanelLoginBox.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLogin.setFont(new java.awt.Font("Lucida Fax", 0, 30)); // NOI18N
        jLabelLogin.setText("Procedura di registrazione");

        jIconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_icon.png"))); // NOI18N

        jTextCognome.setBackground(new java.awt.Color(224, 240, 221));
        jTextCognome.setBorder(javax.swing.BorderFactory.createLineBorder(jButtonLogin.getBackground()));
        jTextCognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCognomeActionPerformed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        jLabelEmail.setText("Indirizzo e-mail : ");

        jLabelPassword.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        jLabelPassword.setText("Password : ");

        jPasswordField1.setBackground(new java.awt.Color(224, 240, 221));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(jButtonLogin.getBackground()));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButtonLogin.setBackground(new java.awt.Color(179, 104, 23));
        jButtonLogin.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("REGISTRATI");
        jButtonLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33), 2));
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jTextEmail.setBackground(new java.awt.Color(224, 240, 221));
        jTextEmail.setBorder(javax.swing.BorderFactory.createLineBorder(jButtonLogin.getBackground()));
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jTextNome.setBackground(new java.awt.Color(224, 240, 221));
        jTextNome.setBorder(javax.swing.BorderFactory.createLineBorder(jButtonLogin.getBackground()));
        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        jLabelNome.setText("Nome : ");

        jLabelCognome.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        jLabelCognome.setText("Cognome : ");

        jPasswordConferma.setBackground(new java.awt.Color(224, 240, 221));
        jPasswordConferma.setBorder(javax.swing.BorderFactory.createLineBorder(jButtonLogin.getBackground()));

        jLabelPassword1.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        jLabelPassword1.setText("Conferma password : ");

        jLabelNomeErr.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelLoginBoxLayout = new javax.swing.GroupLayout(jPanelLoginBox);
        jPanelLoginBox.setLayout(jPanelLoginBoxLayout);
        jPanelLoginBoxLayout.setHorizontalGroup(
            jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPassword1)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelNome)
                            .addComponent(jTextNome, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jLabelCognome)
                            .addComponent(jTextCognome)
                            .addComponent(jTextEmail)
                            .addComponent(jPasswordField1)
                            .addComponent(jPasswordConferma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNomeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabelLogin)))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jIconLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        jPanelLoginBoxLayout.setVerticalGroup(
            jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jIconLogin)
                .addGap(18, 18, 18)
                .addComponent(jLabelLogin)
                .addGap(18, 18, 18)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeErr))
                .addGap(28, 28, 28)
                .addComponent(jLabelCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jPanelLoginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanelLoginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseButtonMouseClicked

    private void jTextCognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCognomeActionPerformed

    private void jLabelCloseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseButtonMouseEntered
        jLabelCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_hover.png")));

    }//GEN-LAST:event_jLabelCloseButtonMouseEntered

    private void jLabelCloseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseButtonMouseExited
        jLabelCloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png")));
     

    }//GEN-LAST:event_jLabelCloseButtonMouseExited

    private void jPanelBodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBodyMouseClicked

    }//GEN-LAST:event_jPanelBodyMouseClicked

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        jLabelNomeErr.setText("Nome non corretto");
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestioneBiblioteca_GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestioneBiblioteca_GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestioneBiblioteca_GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioneBiblioteca_GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestioneBiblioteca_GUI_Register().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonLogin;
    private javax.swing.JLabel jIconLogin;
    private javax.swing.JLabel jLabelCloseButton;
    private javax.swing.JLabel jLabelCognome;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeErr;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLogoBiblioteca;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLoginBox;
    private javax.swing.JPasswordField jPasswordConferma;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextCognome;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
    private MyCanvas m = new MyCanvas();
    
    

}
