/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop_gestionebiblioteca.GUI;

import javax.swing.JFrame;
import oop_gestionebiblioteca.database.Database;

/**
 *
 * @author Benedetto
 */
public class GUI_Admin extends javax.swing.JFrame {

    private Database db;
    public GUI_Admin(Database db) {
        this.db = db;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelAmministrazione = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        jLabelLogout = new javax.swing.JLabel();
        jPanelGestionePrenotazioni2 = new javax.swing.JPanel();
        jLabelGestionePrenotazioniIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelGestionePrenotazioni = new javax.swing.JLabel();
        jPanelGestioneUtenti = new javax.swing.JPanel();
        jLabelUserListIcon1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabelLogo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelLogo.setText("Centro Bibliotecario UniSa");

        jLabelAmministrazione.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAmministrazione.setText("AMMINISTRAZIONE");

        jPanelLogout.setBackground(new java.awt.Color(0, 51, 51));
        jPanelLogout.setForeground(new java.awt.Color(0, 51, 51));

        jLabelLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoutAdminIcon.png"))); // NOI18N
        jLabelLogout.setText(" Logout");
        jLabelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelLogoutLayout = new javax.swing.GroupLayout(jPanelLogout);
        jPanelLogout.setLayout(jPanelLogoutLayout);
        jPanelLogoutLayout.setHorizontalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoutLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelLogout)
                .addContainerGap(703, Short.MAX_VALUE))
        );
        jPanelLogoutLayout.setVerticalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAmministrazione)
                    .addComponent(jLabelLogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAmministrazione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanelGestionePrenotazioni2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGestionePrenotazioni2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 67, 63)));
        jPanelGestionePrenotazioni2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGestionePrenotazioni2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGestionePrenotazioni2MouseClicked(evt);
            }
        });

        jLabelGestionePrenotazioniIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkList.png"))); // NOI18N

        jLabel1.setFont(jLabelGestionePrenotazioni.getFont());
        jLabel1.setText("prenotazioni");

        jLabelGestionePrenotazioni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGestionePrenotazioni.setText("Gestione");

        javax.swing.GroupLayout jPanelGestionePrenotazioni2Layout = new javax.swing.GroupLayout(jPanelGestionePrenotazioni2);
        jPanelGestionePrenotazioni2.setLayout(jPanelGestionePrenotazioni2Layout);
        jPanelGestionePrenotazioni2Layout.setHorizontalGroup(
            jPanelGestionePrenotazioni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionePrenotazioni2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelGestionePrenotazioni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGestionePrenotazioni2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelGestionePrenotazioni))
                    .addGroup(jPanelGestionePrenotazioni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelGestionePrenotazioniIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelGestionePrenotazioni2Layout.setVerticalGroup(
            jPanelGestionePrenotazioni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionePrenotazioni2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGestionePrenotazioniIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGestionePrenotazioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanelGestioneUtenti.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGestioneUtenti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 67, 63)));
        jPanelGestioneUtenti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelUserListIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userListUltimate.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Gestione utenti");

        javax.swing.GroupLayout jPanelGestioneUtentiLayout = new javax.swing.GroupLayout(jPanelGestioneUtenti);
        jPanelGestioneUtenti.setLayout(jPanelGestioneUtentiLayout);
        jPanelGestioneUtentiLayout.setHorizontalGroup(
            jPanelGestioneUtentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestioneUtentiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelGestioneUtentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestioneUtentiLayout.createSequentialGroup()
                        .addComponent(jLabelUserListIcon1)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestioneUtentiLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        jPanelGestioneUtentiLayout.setVerticalGroup(
            jPanelGestioneUtentiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestioneUtentiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserListIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jPanelGestionePrenotazioni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jPanelGestioneUtenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGestionePrenotazioni2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGestioneUtenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelGestionePrenotazioni2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGestionePrenotazioni2MouseClicked

        JFrame newFrame = new GUI_Admin_GestionePrenotazioni(db, this); 
        newFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanelGestionePrenotazioni2MouseClicked

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } */
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Admin().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAmministrazione;
    private javax.swing.JLabel jLabelGestionePrenotazioni;
    private javax.swing.JLabel jLabelGestionePrenotazioniIcon;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelUserListIcon1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGestionePrenotazioni2;
    private javax.swing.JPanel jPanelGestioneUtenti;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLogout;
    // End of variables declaration//GEN-END:variables
}
